# Generated by Django 5.0.7 on 2025-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=60)),
                ('Rut', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=50)),
                ('NombreUsuario', models.CharField(max_length=50)),
                ('ClaveUsuario', models.CharField(max_length=15)),
            ],
        ),
    ]
