# Generated by Django 5.0.7 on 2025-09-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='IdUsuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='NombreUsuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Cantidad_viajes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Telefono',
            field=models.CharField(max_length=20),
        ),
    ]
