# Generated by Django 5.0.7 on 2025-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuarios_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
