# Generated by Django 5.0.7 on 2025-09-11 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarios_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('Cantidad_viajes', models.IntegerField(default=0)),
                ('Recurrente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_usuario',
            fields=[
                ('id_Rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Cantidad_viajes',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Recurrente',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Telefono',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Rol',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.rol_usuario'),
        ),
    ]
