# Generated by Django 5.0.7 on 2025-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientes_rol_usuario_remove_usuarios_cantidad_viajes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
