# Generated by Django 5.0.7 on 2025-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientes_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='Recurrente',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='last_login',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
