# Generated by Django 5.0.7 on 2025-09-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuarios_is_active_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Recurrente',
        ),
    ]
