# Generated by Django 5.0.7 on 2025-09-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usuarios_recurrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año_modelo', models.IntegerField()),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('revision_tecnica_vencimiento', models.DateField()),
                ('soap_vencimiento', models.DateField()),
                ('img_revision', models.ImageField(blank=True, null=True, upload_to='Vehiculos/Revisiones/')),
                ('img_soap', models.ImageField(blank=True, null=True, upload_to='Vehiculos/Soaps/')),
                ('img_permiso_circulacion', models.ImageField(blank=True, null=True, upload_to='Vehiculos/Permisos_circulacion/')),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuarios')),
                ('Telefono', models.CharField(max_length=20)),
                ('img_licencia_conducir', models.ImageField(blank=True, null=True, upload_to='Conductores/Licencias_conduccion/')),
                ('Vencimiento_licencia_conducir', models.DateField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=10)),
                ('Direccion', models.CharField(max_length=50)),
                ('Nacionalidad', models.CharField(max_length=20)),
                ('Edad', models.IntegerField()),
                ('total_viajes_realizados', models.IntegerField(default=0)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehiculos')),
            ],
        ),
    ]
