# Generated by Django 5.0.7 on 2025-09-24 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehiculos_conductores'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='vencimiento_permiso_circulacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
