# Generated by Django 5.0.7 on 2025-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vehiculos_vencimiento_permiso_circulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Comuna', models.CharField(max_length=50)),
                ('Valor', models.IntegerField()),
            ],
        ),
    ]
