# Generated by Django 5.0.7 on 2025-10-02 03:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tarifas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('Id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Cliente', models.CharField(max_length=50)),
                ('Apellidos_Cliente', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('Dirrecion', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Cantidad_pasajeros', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('Cantidad_maletas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('Confirmacion', models.BooleanField(default=False)),
                ('Chofer_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conductores')),
                ('Destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_como_destino', to='core.tarifas')),
                ('Origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_como_origen', to='core.tarifas')),
            ],
        ),
    ]
