# Generated by Django 5.0.7 on 2025-10-02 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reservas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasWeb',
            fields=[
                ('Id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Cliente', models.CharField(max_length=50)),
                ('Apellidos_Cliente', models.CharField(blank=True, default='', max_length=50)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('Dirrecion', models.CharField(blank=True, default='', max_length=100)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Cantidad_pasajeros', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('Cantidad_maletas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('Vehiculo_solicitado', models.CharField(blank=True, default='', max_length=30)),
                ('Comentario', models.TextField(blank=True, default='')),
                ('Confirmacion', models.BooleanField(default=False)),
                ('Creado_en', models.DateTimeField(auto_now_add=True)),
                ('Destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_web_destino', to='core.tarifas')),
                ('Origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_web_origen', to='core.tarifas')),
            ],
        ),
    ]
