# Generated by Django 5.0.7 on 2025-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reservasweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='vencimiento_permiso_circulacion',
            field=models.DateField(),
        ),
    ]
