# Generated by Django 5.0.7 on 2025-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_vehiculos_vencimiento_permiso_circulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='patente',
            field=models.CharField(max_length=10),
        ),
    ]
