# Generated by Django 5.0.7 on 2025-10-04 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_vehiculos_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='Nro_ficha',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='conductores',
            name='img_foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='Conductores/Foto_perfil/'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='estado',
            field=models.CharField(choices=[('REALIZADO', 'realizado'), ('CANCELADO', 'ocupado'), ('PENDIENTE', 'pendiente')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='conductores',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'suspendido')], default='INACTIVO', max_length=10),
        ),
    ]
