# Generated by Django 5.0.7 on 2025-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_conductores_nro_ficha_conductores_img_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='patente',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
