# Generated by Django 5.0.7 on 2025-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_vehiculos_patente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trasporte',
            fields=[
                ('id_trasporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transporte', models.CharField(choices=[('SEDAN', 'sedan'), ('VAN', 'van'), ('SUV', 'suv'), ('LUXURY', 'luxury')], default='SEDAN', max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año_modelo', models.IntegerField()),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('revision_tecnica_vencimiento', models.DateField()),
                ('soap_vencimiento', models.DateField()),
                ('vencimiento_permiso_circulacion', models.DateField()),
                ('img_revision', models.ImageField(blank=True, null=True, upload_to='Vehiculos/Revisiones/')),
                ('img_soap', models.ImageField(blank=True, null=True, upload_to='Vehiculos/Soaps/')),
                ('img_permiso_circulacion', models.ImageField(blank=True, null=True, upload_to='Vehiculos/Permisos_circulacion/')),
            ],
        ),
    ]
