# Generated by Django 5.0.7 on 2025-10-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_trasporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trasporte'),
        ),
    ]
