# Generated by Django 5.0.7 on 2025-10-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_conductores_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='Monto_tarifa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
