# Generated by Django 5.0.7 on 2025-10-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_reservas_monto_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='Monto_tarifa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
