# Generated by Django 5.0.7 on 2025-11-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_reservas_monto_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='nro_vuelo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
