# Generated by Django 5.0.7 on 2025-11-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_reservas_nro_vuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasweb',
            name='nro_vuelo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
