# Generated by Django 5.0.7 on 2025-11-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='Comentario',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservas',
            name='Confirmacion_pagoConductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas',
            name='mediopago',
            field=models.CharField(choices=[('TARJETA', 'tarjeta'), ('EFECTIVO', 'efectivo'), ('TRANSFERENCIA', 'transferencia')], default='tarjeta', max_length=15),
        ),
        migrations.AddField(
            model_name='reservasweb',
            name='Confirmacion_pagoConductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservasweb',
            name='mediopago',
            field=models.CharField(choices=[('TARJETA', 'tarjeta'), ('EFECTIVO', 'efectivo'), ('TRANSFERENCIA', 'transferencia')], default='tarjeta', max_length=15),
        ),
        migrations.AlterField(
            model_name='reservasweb',
            name='Comentario',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
