# Generated by Django 5.0.7 on 2025-11-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='Transferencia_realizada',
            field=models.BooleanField(default=False),
        ),
    ]
