# Generated by Django 5.0.7 on 2025-11-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reservas_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='mediopago',
            field=models.CharField(choices=[('TARJETA', 'tarjeta'), ('EFECTIVO', 'efectivo'), ('TRANSFERENCIA', 'transferencia')], default='tarjeta', max_length=14),
        ),
    ]
