# Generated by Django 5.0.7 on 2025-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reservas_transferencia_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='Comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
