# Generated by Django 5.0.7 on 2025-11-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_reservas_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='Confirmacion_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas',
            name='medio_pago',
            field=models.CharField(choices=[('TARJETA', 'tarjeta'), ('EFECTIVO ', 'efectivo'), ('TRANSFERENCIA', 'tranferencia')], default='tarjeta', max_length=14),
        ),
    ]
