"""
Django settings for tol_project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Cargar variables desde .env sin dependencias extras
def _load_env_file(env_path: Path):
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = val

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Intenta cargar variables desde .env en la raíz del proyecto
_load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-giff@62em9^3)4f#=7eb$c+9avun=!+u-4%k#1xoa-ftz%^q0u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.ngrok-free.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://mandi-precostal-imagistically.ngrok-free.dev"
]
# ⭐ AÑADE ESTA CONFIGURACIÓN PARA CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',  # Comodín para ngrok (recomendado)
    # O, de forma específica:
    # 'https://mandi-precostal-imagistically.ngrok-free.dev' 
]

ROOT_URLCONF = 'tol_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tol_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.oracle",
        "NAME": "xe",
        "USER": "C##ADMIN_LETCO",
        "PASSWORD": "admin12",
        "HOST": "localhost",
        "PORT": "1521",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators


# tol_project/settings.py
AUTHENTICATION_BACKENDS = [
    'core.backends.RutAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Redirecciones de autenticación en Django
# ----------------------------------------
# Cuando un usuario inicia sesión correctamente:
LOGIN_REDIRECT_URL = 'admin_config'       # o 'admin_config' si quieres que vaya directo al panel admin

# Cuando un usuario intenta entrar a una vista protegida sin estar logueado:
LOGIN_URL = 'login'

# Cuando un usuario cierra sesión:
LOGOUT_REDIRECT_URL = 'inicio'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de archivos de medios (subidas por el usuario)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración de email (Brevo por defecto si hay credenciales en el entorno)
BREVO_SMTP_HOST = os.getenv("BREVO_SMTP_HOST", "smtp-relay.brevo.com")
BREVO_SMTP_PORT = int(os.getenv("BREVO_SMTP_PORT", "587"))
BREVO_SMTP_USER = os.getenv("BREVO_SMTP_USER")
BREVO_SMTP_PASS = os.getenv("BREVO_SMTP_PASS")
BREVO_DEFAULT_FROM = os.getenv("BREVO_DEFAULT_FROM")

if BREVO_SMTP_USER and BREVO_SMTP_PASS:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = BREVO_SMTP_HOST
    EMAIL_PORT = BREVO_SMTP_PORT
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = BREVO_SMTP_USER
    EMAIL_HOST_PASSWORD = BREVO_SMTP_PASS
    DEFAULT_FROM_EMAIL = BREVO_DEFAULT_FROM or BREVO_SMTP_USER
else:
    # Sin credenciales definidas, no intentamos enviar y caemos a consola.
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "no-reply@tol.local"
